[package]
name = "turing-wasm"
version = "0.1.0"
authors = ["beaarend <beaarend@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
turing = {path = "../turing/"}